/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TXT_H_RPCGEN
#define	_TXT_H_RPCGEN

#include <rpc/rpc.h>
#define	MAX_STR 256

struct text_record {
	char *element_text;
};
typedef struct text_record text_record;

#define	TXTPROG ((unsigned long)(0x20000001))
#define	TXTVERS ((unsigned long)(1))
#define	AddElement ((unsigned long)(1))
extern  int * addelement_1();
#define	ShowElement ((unsigned long)(2))
extern  char ** showelement_1();
extern int txtprog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_text_record();

#endif /* !_TXT_H_RPCGEN */
