/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define	_DATE_H_RPCGEN

#include <rpc/rpc.h>

#define	MY_DATE_PROG ((unsigned long)(0x31234567))
#define	DATE_VERS ((unsigned long)(1))
#define	BIN_DATE ((unsigned long)(1))
extern  long * bin_date_1();
#define	STR_DATE ((unsigned long)(2))
extern  char ** str_date_1();
extern int my_date_prog_1_freeresult();

#endif /* !_DATE_H_RPCGEN */
