/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define	_DATE_H_RPCGEN

#include <rpc/rpc.h>

#define	TEXT_SERVER ((unsigned long)(0x32345678))
#define	TEXT_VERS ((unsigned long)(1))
#define	ADD_ELEMENT ((unsigned long)(1))
extern  int * add_element_1();
#define	SHOW_ELEMENT ((unsigned long)(2))
extern  char ** show_element_1();
extern int text_server_1_freeresult();

#endif /* !_DATE_H_RPCGEN */
